#
# Extracts some of the interesting Pull Request metadata out of the JSON into individual files, making it easier to consume.
#

---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: public.ecr.aws/ons-spp/concourse-init-metadata
    tag: 1

inputs:
  - name: repo

outputs:
  - name: repo

run:
  path: sh
  args:
    - -exc
    - |
      apk add --update --no-progress bash jq
      bash ./repo/ci/tasks/terraform/init_metadata.sh