---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: public.ecr.aws/ons-spp/terraform
    tag: 1

inputs:
  - name: repo_built
  - name: GITHUB_OUTPUT
run:
  path: sh
  dir: repo_built
  args:
    - -exc
    - |
      ls
      apk add --update --no-progress bash jq
      apk add --no-cache --no-progress aws-cli
      bash ./ci/tasks/terraform/init_metadata.sh
      bash ./ci/tasks/build_and_deploy/deploy.sh
