# This is the pipeline to run the BDD tests on prod, pre-prod and dev. 
# The triggers are daily
# The triggers are daily for now, a ticket has been written to address push to branch triggers.
resources:
  - name: main
    type: git
    icon: github
    check_every: never
    webhook_token: gesture
    source:
      uri: https://github.com/ONSdigital/sml-catalogue.git
      branch: SPP-9145-concourse-BDD-test-report
      username: ((github_access_token))
      password: x-oauth-basic
  # - name: bdd-test-timer
  #   type: time
  #   source:
  #     # Triggers the tests once per day, just after 7:30am.
  #     start: 7:30
  #     stop: 7:45
  #     location: Europe/London
  #     days: [Monday, Tuesday, Wednesday, Thursday, Friday]

jobs:
  - name: dev-bdd-tests
    plan:
      # - get: bdd-test-timer
      #   trigger: true
      - get: main
      - task: run-acceptance-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: public.ecr.aws/ons-spp/python-selenium
              tag: 4
          params:
            {ENDPOINT: 'https://d1jgbw8ee9pybj.cloudfront.net/'}
          inputs:
            - name: main
          run:
            path: sh
            dir: main
            args:
            - -exc
            - |
              pip install pipenv
              pipenv install --dev
              date=$(date '+%Y_%m_%d')
              echo $date
              mkdir -p ./features/test_reports/dev/$date
              pipenv run behave -D host=$ENDPOINT --junit --junit-directory ./features/test_reports/dev/$date
              cd ./features/test_reports/dev/$date
              ls
              cat ./features/test_reports/dev/$date/TESTS-about.xml
              cat ./features/test_reports/dev/$date/TESTS-accessibility.xml
              cat ./features/test_reports/dev/$date/TESTS-cookies.xml
              cat ./features/test_reports/dev/$date/TESTS-footer.xml
              cat ./features/test_reports/dev/$date/TESTS-glossary.xml
              cat ./features/test_reports/dev/$date/TESTS-header.xml
              cat ./features/test_reports/dev/$date/TESTS-help_center.xml
              cat ./features/test_reports/dev/$date/TESTS-method_summary.xml
              cat ./features/test_reports/dev/$date/TESTS-methods.xml