# This is the pipeline to run the BDD tests on prod, pre-prod and dev.
# The triggers are daily for now, a ticket has been written to address push to branch triggers.
resources:
  - name: main
    type: git
    icon: github
    check_every: never
    webhook_token: gesture
    source:
      uri: https://github.com/ONSdigital/sml-catalogue.git
      branch: main
      username: ((github_access_token))
      password: x-oauth-basic
  - name: bdd-test-timer
    type: time
    source:
      # Triggers the tests once per day, just after 7:30am.
      start: 7:30
      stop: 7:45
      location: Europe/London
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]

jobs:
  - name: preprod-bdd-tests
    plan:
      - get: bdd-test-timer
        trigger: true
      - get: main
      - task: run-acceptance-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: public.ecr.aws/ons-spp/python-selenium
              tag: 4
          params:
            {ENDPOINT: 'https://preprod-sml.aws.onsdigital.uk/'}
          inputs:
            - name: main
          run:
            path: sh
            dir: main
            args:
            - -exc
            - |
              pip install pipenv
              pipenv install --dev
              date=$(date '+%Y_%m_%d')
              echo $date
              mkdir -p ./features/test_reports/preprod/$date
              pipenv run behave -D host=$ENDPOINT --junit --junit-directory ./features/test_reports/preprod/$date
              cd ./features/test_reports/preprod/$date
              ls
              cat TESTS-about.xml TESTS-accessibility.xml TESTS-cookies.xml TESTS-footer.xml TESTS-glossary.xml TESTS-header.xml TESTS-help_center.xml TESTS-method_summary.xml TESTS-methods.xml > test_report.xml
              cat test_report.xml

  - name: prod-bdd-tests
    plan:
      - get: bdd-test-timer
        trigger: true
      - get: main
      - task: run-acceptance-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: public.ecr.aws/ons-spp/python-selenium
              tag: 4
          params:
            {ENDPOINT: 'https://statisticalmethodslibrary.ons.gov.uk/'}
          inputs:
            - name: main
          run:
            path: sh
            dir: main
            args:
            - -exc
            - |
              pip install pipenv
              pipenv install --dev
              date=$(date '+%Y_%m_%d')
              echo $date
              mkdir -p ./features/test_reports/prod/$date
              pipenv run behave -D host=$ENDPOINT --junit --junit-directory ./features/test_reports/prod/$date
              cd ./features/test_reports/prod/$date
              ls
              cat TESTS-about.xml TESTS-accessibility.xml TESTS-cookies.xml TESTS-footer.xml TESTS-glossary.xml TESTS-header.xml TESTS-help_center.xml TESTS-method_summary.xml TESTS-methods.xml > test_report.xml
              cat test_report.xml