# This is the pipeline to run the BDD tests on prod, pre-prod and dev. 
# The triggers are manual for now, a ticket has been written to address this.
resources:
  - name: main
    type: git
    icon: github
    check_every: never
    webhook_token: gesture
    source:
      uri: https://github.com/ONSdigital/sml-catalogue.git
      branch: main
      username: ((github_access_token))
      password: x-oauth-basic

jobs:
  - name: dev-bdd-tests
    plan:
      - get: main
      - task: run-acceptance-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: jasonbellons/python_3_slim
              tag: 311test
          params:
            {ENDPOINT: 'https://d1jgbw8ee9pybj.cloudfront.net/'}
          inputs:
            - name: main
          run:
            path: sh
            dir: main
            args:
            - -exc
            - |
              python --version
              pipenv install --dev
              pipenv run behave -D host=$ENDPOINT

  - name: preprod-bdd-tests
    plan:
      - get: main
      - task: run-acceptance-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: jasonbellons/python_3_slim
              tag: 3
          params:
            {ENDPOINT: 'https://preprod-sml.aws.onsdigital.uk/'}
          inputs:
            - name: main
          run:
            path: sh
            dir: main
            args:
            - -exc
            - |
              python --version
              pipenv install --dev
              pipenv run behave -D host=$ENDPOINT

  - name: prod-bdd-tests
    plan:
      - get: main
      - task: run-acceptance-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: jasonbellons/python_3_slim
              tag: 3
          params:
            {ENDPOINT: 'https://statisticalmethodslibrary.ons.gov.uk/'}
          inputs:
            - name: main
          run:
            path: sh
            dir: main
            args:
            - -exc
            - |
              python --version
              pipenv install --dev
              pipenv run behave -D host=$ENDPOINT
