# This is the pipeline to run the BDD tests on prod, pre-prod and dev. 
# The triggers are daily
# BDD test reports are added as part of the pipeline run
resources:
  - name: main
    type: git
    icon: github
    check_every: never
    webhook_token: gesture
    source:
      uri: https://github.com/ONSdigital/sml-catalogue.git
      branch: SPP-9145-concourse-BDD-test-reports
      username: ((github_access_token))
      password: x-oauth-basic

jobs:
  - name: dev-bdd-tests
    plan:
      - get: main
      - task: run-acceptance-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: public.ecr.aws/ons-spp/python-selenium
              tag: 4
          params:
            {ENDPOINT: 'https://d1jgbw8ee9pybj.cloudfront.net/'}
          inputs:
            - name: main
          run:
            path: sh
            dir: main
            args:
            - -exc
            - |
              pip install pipenv
              pipenv install --dev
              echo "Creating report directory"
              cd ./features/test_reports/dev
              date=$(date '+%Y_%m_%d')
              echo $date
              mkdir -p $date
              echo "cd to directory"
              cd $date
              pipenv run behave -D host=$ENDPOINT --junit
              echo "Create overview report"
              junit2html ./reports/ --merge reports/report.xml
              junit2html ./reports/report.xml reports/report.html
              echo "Remove junk files"
              cd ./reports
              find . -name "*.xml" -type f|xargs rm -f
              echo Push to branch
              git add .
              git commit -m "Test report update"
              git push

  - name: preprod-bdd-tests
    plan:
      - get: main
      - task: run-acceptance-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: public.ecr.aws/ons-spp/python-selenium
              tag: 4
          params:
            {ENDPOINT: 'https://preprod-sml.aws.onsdigital.uk/'}
          inputs:
            - name: main
          run:
            path: sh
            dir: main
            args:
            - -exc
            - |
              pip install pipenv
              pipenv install --dev
              echo "Creating report directory"
              cd features/test_reports/preprod
              date=$(date '+%Y_%m_%d')
              echo $date
              mkdir -p $date
              echo "cd to directory"
              cd $date
              pipenv run behave -D host=$ENDPOINT --junit
              echo "Create overview report"
              junit2html ./reports/ --merge reports/report.xml
              junit2html ./reports/report.xml reports/report.html
              echo "Remove junk files"
              cd ./reports
              find . -name "*.xml" -type f|xargs rm -f
              echo Push to branch
              git add .
              git commit -m "Test report update"
              git push

  - name: prod-bdd-tests
    plan:
      - get: main
      - task: run-acceptance-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: public.ecr.aws/ons-spp/python-selenium
              tag: 4
          params:
            {ENDPOINT: 'https://statisticalmethodslibrary.ons.gov.uk/'}
          inputs:
            - name: main
          run:
            path: sh
            dir: main
            args:
            - -exc
            - |
              pip install pipenv
              pipenv install --dev
              echo "Creating report directory"
              cd features/test_reports/prod
              date=$(date '+%Y_%m_%d')
              echo $date
              mkdir -p $date
              echo "cd to directory"
              cd $date
              pipenv run behave -D host=$ENDPOINT --junit
              echo "Create overview report"
              junit2html ./reports/ --merge reports/report.xml
              junit2html ./reports/report.xml reports/report.html
              echo "Remove junk files"
              cd ./reports
              find . -name "*.xml" -type f|xargs rm -f
              echo Push to branch
              git add .
              git commit -m "Test report update"
              git push
