---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: public.ecr.aws/ons-spp/python-selenium
    tag: 4

inputs:
  - name: repo
  - name: GITHUB_OUTPUT

run:
  path: sh
  dir: repo
  args:
    - -exc
    - |
      export URL=$(sed -n 1p ../GITHUB_OUTPUT/output.txt | cut -d " " -f1 | cut -c 12-)
      bash ./ci/tasks/testing/run_bdd_tests.sh
